export interface NFLTeam {
  id: string;
  name: string;
  abbreviation: string;
  displayName: string;
  shortDisplayName: string;
  city: string;
  color: string;
  alternateColor: string;
  logo: string;
}

// ESPN API Team IDs and Colors (verified against ESPN API)
export const NFL_TEAMS: Record<string, NFLTeam> = {
  '1': {
    id: '1',
    name: 'Falcons',
    abbreviation: 'ATL',
    displayName: 'Atlanta Falcons',
    shortDisplayName: 'Falcons',
    city: 'Atlanta',
    color: 'A71930',
    alternateColor: '000000',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/atl.png',
  },
  '2': {
    id: '2',
    name: 'Bills',
    abbreviation: 'BUF',
    displayName: 'Buffalo Bills',
    shortDisplayName: 'Bills',
    city: 'Buffalo',
    color: '00338D',
    alternateColor: 'D50A0A',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/buf.png',
  },
  '3': {
    id: '3',
    name: 'Bears',
    abbreviation: 'CHI',
    displayName: 'Chicago Bears',
    shortDisplayName: 'Bears',
    city: 'Chicago',
    color: '0B1C3A',
    alternateColor: 'E64100',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/chi.png',
  },
  '4': {
    id: '4',
    name: 'Bengals',
    abbreviation: 'CIN',
    displayName: 'Cincinnati Bengals',
    shortDisplayName: 'Bengals',
    city: 'Cincinnati',
    color: 'FB4F14',
    alternateColor: '000000',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/cin.png',
  },
  '5': {
    id: '5',
    name: 'Browns',
    abbreviation: 'CLE',
    displayName: 'Cleveland Browns',
    shortDisplayName: 'Browns',
    city: 'Cleveland',
    color: '472A08',
    alternateColor: 'FF3C00',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/cle.png',
  },
  '6': {
    id: '6',
    name: 'Cowboys',
    abbreviation: 'DAL',
    displayName: 'Dallas Cowboys',
    shortDisplayName: 'Cowboys',
    city: 'Dallas',
    color: '002A5C',
    alternateColor: 'B0B7BC',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/dal.png',
  },
  '7': {
    id: '7',
    name: 'Broncos',
    abbreviation: 'DEN',
    displayName: 'Denver Broncos',
    shortDisplayName: 'Broncos',
    city: 'Denver',
    color: '0A2343',
    alternateColor: 'FC4C02',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/den.png',
  },
  '8': {
    id: '8',
    name: 'Lions',
    abbreviation: 'DET',
    displayName: 'Detroit Lions',
    shortDisplayName: 'Lions',
    city: 'Detroit',
    color: '0076B6',
    alternateColor: 'BBBBBB',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/det.png',
  },
  '9': {
    id: '9',
    name: 'Packers',
    abbreviation: 'GB',
    displayName: 'Green Bay Packers',
    shortDisplayName: 'Packers',
    city: 'Green Bay',
    color: '204E32',
    alternateColor: 'FFB612',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/gb.png',
  },
  '10': {
    id: '10',
    name: 'Titans',
    abbreviation: 'TEN',
    displayName: 'Tennessee Titans',
    shortDisplayName: 'Titans',
    city: 'Tennessee',
    color: '4B92DB',
    alternateColor: '002A5C',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/ten.png',
  },
  '11': {
    id: '11',
    name: 'Colts',
    abbreviation: 'IND',
    displayName: 'Indianapolis Colts',
    shortDisplayName: 'Colts',
    city: 'Indianapolis',
    color: '003B75',
    alternateColor: 'FFFFFF',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/ind.png',
  },
  '12': {
    id: '12',
    name: 'Chiefs',
    abbreviation: 'KC',
    displayName: 'Kansas City Chiefs',
    shortDisplayName: 'Chiefs',
    city: 'Kansas City',
    color: 'E31837',
    alternateColor: 'FFB612',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/kc.png',
  },
  '13': {
    id: '13',
    name: 'Raiders',
    abbreviation: 'LV',
    displayName: 'Las Vegas Raiders',
    shortDisplayName: 'Raiders',
    city: 'Las Vegas',
    color: '000000',
    alternateColor: 'A5ACAF',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/lv.png',
  },
  '14': {
    id: '14',
    name: 'Rams',
    abbreviation: 'LAR',
    displayName: 'Los Angeles Rams',
    shortDisplayName: 'Rams',
    city: 'Los Angeles',
    color: '003594',
    alternateColor: 'FFD100',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/lar.png',
  },
  '15': {
    id: '15',
    name: 'Dolphins',
    abbreviation: 'MIA',
    displayName: 'Miami Dolphins',
    shortDisplayName: 'Dolphins',
    city: 'Miami',
    color: '008E97',
    alternateColor: 'FC4C02',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/mia.png',
  },
  '16': {
    id: '16',
    name: 'Vikings',
    abbreviation: 'MIN',
    displayName: 'Minnesota Vikings',
    shortDisplayName: 'Vikings',
    city: 'Minnesota',
    color: '4F2683',
    alternateColor: 'FFC62F',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/min.png',
  },
  '17': {
    id: '17',
    name: 'Patriots',
    abbreviation: 'NE',
    displayName: 'New England Patriots',
    shortDisplayName: 'Patriots',
    city: 'New England',
    color: '002A5C',
    alternateColor: 'C60C30',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/ne.png',
  },
  '18': {
    id: '18',
    name: 'Saints',
    abbreviation: 'NO',
    displayName: 'New Orleans Saints',
    shortDisplayName: 'Saints',
    city: 'New Orleans',
    color: 'D3BC8D',
    alternateColor: '000000',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/no.png',
  },
  '19': {
    id: '19',
    name: 'Giants',
    abbreviation: 'NYG',
    displayName: 'New York Giants',
    shortDisplayName: 'Giants',
    city: 'New York',
    color: '003C7F',
    alternateColor: 'C9243F',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/nyg.png',
  },
  '20': {
    id: '20',
    name: 'Jets',
    abbreviation: 'NYJ',
    displayName: 'New York Jets',
    shortDisplayName: 'Jets',
    city: 'New York',
    color: '115740',
    alternateColor: 'FFFFFF',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/nyj.png',
  },
  '21': {
    id: '21',
    name: 'Eagles',
    abbreviation: 'PHI',
    displayName: 'Philadelphia Eagles',
    shortDisplayName: 'Eagles',
    city: 'Philadelphia',
    color: '06424D',
    alternateColor: '000000',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/phi.png',
  },
  '22': {
    id: '22',
    name: 'Cardinals',
    abbreviation: 'ARI',
    displayName: 'Arizona Cardinals',
    shortDisplayName: 'Cardinals',
    city: 'Arizona',
    color: 'A40227',
    alternateColor: 'FFFFFF',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/ari.png',
  },
  '23': {
    id: '23',
    name: 'Steelers',
    abbreviation: 'PIT',
    displayName: 'Pittsburgh Steelers',
    shortDisplayName: 'Steelers',
    city: 'Pittsburgh',
    color: '000000',
    alternateColor: 'FFB612',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/pit.png',
  },
  '24': {
    id: '24',
    name: 'Chargers',
    abbreviation: 'LAC',
    displayName: 'Los Angeles Chargers',
    shortDisplayName: 'Chargers',
    city: 'Los Angeles',
    color: '0080C6',
    alternateColor: 'FFC20E',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/lac.png',
  },
  '25': {
    id: '25',
    name: '49ers',
    abbreviation: 'SF',
    displayName: 'San Francisco 49ers',
    shortDisplayName: '49ers',
    city: 'San Francisco',
    color: 'AA0000',
    alternateColor: 'B3995D',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/sf.png',
  },
  '26': {
    id: '26',
    name: 'Seahawks',
    abbreviation: 'SEA',
    displayName: 'Seattle Seahawks',
    shortDisplayName: 'Seahawks',
    city: 'Seattle',
    color: '002A5C',
    alternateColor: '69BE28',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/sea.png',
  },
  '27': {
    id: '27',
    name: 'Buccaneers',
    abbreviation: 'TB',
    displayName: 'Tampa Bay Buccaneers',
    shortDisplayName: 'Buccaneers',
    city: 'Tampa Bay',
    color: 'BD1C36',
    alternateColor: '3E3A35',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/tb.png',
  },
  '28': {
    id: '28',
    name: 'Commanders',
    abbreviation: 'WAS',
    displayName: 'Washington Commanders',
    shortDisplayName: 'Commanders',
    city: 'Washington',
    color: '5A1414',
    alternateColor: 'FFB612',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/wsh.png',
  },
  '29': {
    id: '29',
    name: 'Panthers',
    abbreviation: 'CAR',
    displayName: 'Carolina Panthers',
    shortDisplayName: 'Panthers',
    city: 'Carolina',
    color: '0085CA',
    alternateColor: '000000',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/car.png',
  },
  '30': {
    id: '30',
    name: 'Jaguars',
    abbreviation: 'JAX',
    displayName: 'Jacksonville Jaguars',
    shortDisplayName: 'Jaguars',
    city: 'Jacksonville',
    color: '007487',
    alternateColor: 'D7A22A',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/jax.png',
  },
  '33': {
    id: '33',
    name: 'Ravens',
    abbreviation: 'BAL',
    displayName: 'Baltimore Ravens',
    shortDisplayName: 'Ravens',
    city: 'Baltimore',
    color: '29126F',
    alternateColor: '000000',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/bal.png',
  },
  '34': {
    id: '34',
    name: 'Texans',
    abbreviation: 'HOU',
    displayName: 'Houston Texans',
    shortDisplayName: 'Texans',
    city: 'Houston',
    color: '00143F',
    alternateColor: 'C41230',
    logo: 'https://a.espncdn.com/i/teamlogos/nfl/500/hou.png',
  },
};

export const getTeamById = (id: string): NFLTeam | undefined => {
  return NFL_TEAMS[id];
};

export const getAllTeams = (): NFLTeam[] => {
  return Object.values(NFL_TEAMS).sort((a, b) =>
    a.displayName.localeCompare(b.displayName)
  );
};
